In [9]:
#naive b

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,accuracy_score
#read csv file
dataset = pd.read_csv('Book1.csv')
#take data and target using their index position
X = dataset.iloc[:, [1, 2]].values
y = dataset.iloc[:, -1].values
print("\n------------------\ndata\n------------------\n")
print(X)
print("\n------------------\ntarget\n------------------\n")
print(y)
#to convert data and target to dummy code
le = LabelEncoder()
print("\n------------------\ndummy code of data\n------------------\n")
k=le.fit_transform(X[:,0])
print(k)
k=le.fit_transform(X[:,0])
f=le.fit_transform(X[:,1])
print(f)
print("\n------------------\ndummy code of target\n------------------\n")
label=le.fit_transform(y)
print(label)
print("\n------------------\njoin 2 set of data(dummy code) \n------------------\n")
q=(np.vstack((k, f)).T)
print(q)
X_train, X_test, y_train, y_test = train_test_split(q, label, test_size = 0.20, random_state =42)
classifier = GaussianNB()
classifier.fit(X_train, y_train)
#predict the future
print("\n------------------\npredict target and actualtarget\n------------------\n")
y_pred=classifier.predict(X_test)
print(y_pred)
print("\n\n")
print(y_test)
#test the accurence
print("\n------------------\naccurency of train data and target\n------------------\n")
print(classifier.score(X_train,y_train))
print("\n------------------\naccurency of test data and target\n------------------\n")
print(classifier.score(X_test,y_test))



------------------
data
------------------

[['sunny' 'hot']
 ['sunny' 'hot']
 ['overcast' 'hot']
 ['rainy' 'mild']
 ['rainy' 'cool']
 ['rainy' 'cool']
 ['overcast' 'cool']
 ['sunny' 'mild']
 ['sunny' 'cool']
 ['rainy' 'mild']
 ['sunny' 'mild']
 ['overcast' 'mild']
 ['overcast' 'hot']
 ['rainy' 'mild']]

------------------
target
------------------

['no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes'
 'no']

------------------
dummy code of data
------------------

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]

------------------
dummy code of target
------------------

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]

------------------
join 2 set of data(dummy code) 
------------------

[[2 1]
 [2 1]
 [0 1]
 [1 2]
 [1 0]
 [1 0]
 [0 0]
 [2 2]
 [2 0]
 [1 2]
 [2 2]
 [0 2]
 [0 1]
 [1 2]]

------------------
predict target and actualtarget
------------------

[0 1 0]



[1 1 0]

------------------
accurency of train data and target
------------------

0.7272727272727273