In [1]:
#svd
from scipy.linalg import svd
import numpy as np
a=np.arange(9).reshape((3,3))
u,s,t=svd(a)
print("3 matrix from a matrix:\n")
print(u)
print("\n")
print(s)
print("\n")
print(t)

3 matrix from a matrix:

[[-0.13511895  0.90281571  0.40824829]
 [-0.49633514  0.29493179 -0.81649658]
 [-0.85755134 -0.31295213  0.40824829]]


[1.42267074e+01 1.26522599e+00 4.97902781e-16]


[[-0.4663281  -0.57099079 -0.67565348]
 [-0.78477477 -0.08545673  0.61386131]
 [-0.40824829  0.81649658 -0.40824829]]
