In [1]:
#matrix multipliacation
import numpy as np
print("\nfirst matrix:")
a=np.arange(9).reshape((3,3))
print(a)
print("\nsecond matrix:")
b=np.arange(9).reshape((3,3))
print(b)
print("\nmultiplication:")
c=np.dot(a,b)
print(c)
print("\ntransepose:")
d=np.transpose(c)
print(d)


first matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

second matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

multiplication:
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

transepose:
[[ 15  42  69]
 [ 18  54  90]
 [ 21  66 111]]
